version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "[Action]"
    schedule:
      interval: "monthly"

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "rust"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "[Docker]"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[Cargo]"
